export const GET_VIDEOGAMES="GET_VIDEOGAMES";
export const PAGINATE="PAGINATE";
export const ORDER="ORDER";
export const GET_VIDEOGAMES_ID= "GET_VIDEOGAMES_ID";
export const GET_VIDEOGAMES_NAME="GET_VIDEOGAMES_NAME";
export const GET_VIDEOGAMES_GENRES="GET_VIDEOGAMES_GENRES";
export const POST_VIDEOGAMES="POST_VIDEOGAMES";
export const CLEAR="CLEAR";